/**
 * @trustpulse/sdk - Typed Error Architecture
 *
 * All errors generated by the TrustPulse SDK inherit from BaseSDKError.
 * Sensitive data (passwords, tokens, raw keystrokes) are NEVER included in error messages.
 */

export abstract class BaseSDKError extends Error {
  public abstract readonly code: string;
  public readonly timestamp: number;

  constructor(message: string) {
    super(`[TrustPulse] ${message}`);
    this.name = this.constructor.name;
    this.timestamp = Date.now();
    Object.setPrototypeOf(this, new.target.prototype);
  }
}

export class ConfigurationError extends BaseSDKError {
  public readonly code = "CONFIGURATION_ERROR";
}

export class SDKInitializationError extends BaseSDKError {
  public readonly code = "INITIALIZATION_ERROR";
}

export class SessionBindingError extends BaseSDKError {
  public readonly code = "SESSION_BINDING_ERROR";
}

export class TelemetryValidationError extends BaseSDKError {
  public readonly code = "TELEMETRY_VALIDATION_ERROR";
}

export class TransportError extends BaseSDKError {
  public readonly code = "TRANSPORT_ERROR";
  public readonly status?: number;

  constructor(message: string, status?: number) {
    super(message);
    this.status = status;
  }
}

export class PrivacyConfigurationError extends BaseSDKError {
  public readonly code = "PRIVACY_CONFIG_ERROR";
}
